/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 2014-11-27, 20:51:22
 */

package session2;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.Scanner;
import java.io.File;
/**
 *
 * @author Mark
 */
public class Main extends javax.swing.JFrame {
    private static Admin ad = new Admin("Admin", "888888");//初始化管理员
    public static Saler[] sl = new Saler[10];//初始化员工数组
    /*public static ItemList[] Item = new ItemList[50];*/

    public static int goods = 0;
    public static int clerk = 5;
    
    public static double lim = 0.1;
    public static double mn = 200000;

    public static Main pad = new Main();

    /** Creates new form Main */
    public Main() {
        ini();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("苹果专卖店");
        setBounds(new java.awt.Rectangle(280, 280, 437, 350));
        setMinimumSize(new java.awt.Dimension(437, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/session2/123.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 150);

        jPanel2.setLayout(null);

        jTextField1.setText("Account");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(20, 30, 180, 30);
        jTextField1.getAccessibleContext().setAccessibleName("");

        jPasswordField1.setEchoChar('\0');
        jPasswordField1.setText("Password");
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(20, 60, 180, 30);

        jButton1.setText("LOGIN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(51, 100, 120, 23);

        jTabbedPane1.addTab("Admin", jPanel2);

        jPanel3.setLayout(null);

        jTextField2.setText("Account");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel3.add(jTextField2);
        jTextField2.setBounds(20, 30, 180, 30);

        jPasswordField2.setEchoChar('\0');
        jPasswordField2.setText("Password");
        jPasswordField2.setToolTipText("");
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        jPanel3.add(jPasswordField2);
        jPasswordField2.setBounds(20, 60, 180, 30);

        jButton2.setText("LOGIN");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(51, 100, 120, 23);

        jTabbedPane1.addTab("Saler", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(140, 150, 290, 170);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/session2/head/initial.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 150, 140, 170);

        getAccessibleContext().setAccessibleName("jframe");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        checkad(jTextField1.getText(),String.valueOf(jPasswordField1.getPassword()));
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        checksl(jTextField2.getText(),String.valueOf(jPasswordField2.getPassword()));
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        if (jTextField2.getText().equals("")) jTextField2.setText("Account");
        else{
            int tmp = getsl(jTextField2.getText()) ;
            if (tmp != -1) {
                jLabel2.setIcon(sl[tmp].getIcon());
            }
            else jLabel2.setIcon(ad.geticon());
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
        jPasswordField2.setText(null);
        jPasswordField2.setEchoChar('\u25cf');
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        jPasswordField1.setText(null);
        jPasswordField1.setEchoChar('\u25cf');
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if (jTextField1.getText().equals("")) jTextField1.setText("Account");
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) checkad(jTextField1.getText(),String.valueOf(jPasswordField1.getPassword()));
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) checksl(jTextField2.getText(),String.valueOf(jPasswordField2.getPassword()));
    }//GEN-LAST:event_jButton2KeyPressed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) checkad(jTextField1.getText(),String.valueOf(jPasswordField1.getPassword()));
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) checksl(jTextField2.getText(),String.valueOf(jPasswordField2.getPassword()));
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/session2/head/initial.jpg")));
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained

    /**
    * @param args the command line arguments
    */

    private void checkad(String str, String pass){
        if (str.equals("admin")&&(pass.equals(ad.getpass()))) {
            this.setVisible(false); 
            jTextField1.setText(null); jPasswordField1.setText(null);
            ad.main(); }
        else JOptionPane.showMessageDialog(rootPane, "Wrong Password!\n\nPlease try again!", "Warning", JOptionPane.WARNING_MESSAGE);
    }//Now, it's a regex example.  It's original for check the password

    private int getsl(String str){
        for (int i = 0; i< clerk; i++){
            if (sl[i].getnm().equals(str)) return i;
        }
        return -1;
    }
    private void checksl(String str, String pass){
        int tmp = getsl(str); 
        if (tmp == -1) JOptionPane.showMessageDialog(rootPane, "Member not EXIST", "Warning", JOptionPane.WARNING_MESSAGE);
        else  if (! sl[tmp].getpass().equals(pass)) JOptionPane.showMessageDialog(rootPane, "Wrong Password!\n\nPlease try again!", "Warning", JOptionPane.WARNING_MESSAGE);
        else  {this.setVisible(false); 
        jTextField2.setText(null); jPasswordField2.setText(null); jPanel2.updateUI();
        sl[tmp].main();}
    }


    private void ini(){
        Scanner input = null;
        try {
            input = new Scanner(new File(System.getProperty("user.dir") + "\\Storage.in"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

         for (int i = 0; i < 5; i++){
             String tmp = String.format("%s%02d", "10", i + 1);
             sl[i] = new Saler(tmp, tmp);
         }
        while (input.hasNext()){
            Storage.arr[goods] = input.nextLine(); //System.out.println(input.next());
            Storage.price[goods] = Double.parseDouble(input.next());
            Storage.piece[goods] = Integer.parseInt(input.next());
            input.nextLine(); 
            goods++;
        }
        Storage.proto = java.util.Arrays.copyOf(Storage.price, Storage.price.length);
         /*Item[0] = new ItemList("ipad mini 2", 2500, 20);
         Item[1] = new ItemList("ipadair", 3100, 20);
         Item[2] = new ItemList("iphone 5C", 2900, 20);
         Item[3] = new ItemList("iphone 5", 3500, 20);
         Item[4] = new ItemList("iphone5S", 4300,20);*/
         /*Storage.arr[0] = "ipad mini 2"; Storage.price[0] = 2500; Storage.piece[0] = 20;
         Storage.arr[1] = "ipad air"; Storage.price[1] = 3100;  Storage.piece[1] = 20;
         Storage.arr[2] = "iphone 5C"; Storage.price[2] = 2900;  Storage.piece[2] = 20;
         Storage.arr[3] = "iphone 5"; Storage.price[3] = 3500; Storage.piece[3] = 20;
         Storage.arr[4] = "iphone 5S"; Storage.price[4] = 4300;  Storage.piece[4] = 20;
         Storage.proto = java.util.Arrays.copyOf(Storage.price, Storage.price.length);*/
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                int w = (Toolkit.getDefaultToolkit().getScreenSize().width - 437) / 2;
                    int h = (Toolkit.getDefaultToolkit().getScreenSize().height - 350) / 2;
                    pad.setLocation(w, h);
                    pad.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
